### ISSUE TITLE
How to install dydxprotocol/v3-client please ?

### ISSUE THREAD

**Issue by Ulawun** [dydxprotocol/v3-client#157]
Hello,
I can't install dydxprotocol/v3-client :-(
I'm using:
- OS: Linux Mint 20.3 - Mate 64-bit
- npm version: 8.4.0

I created a frech local directory.
To install I tried the 2 commands:
1) npm i -s @dydxprotocol/v3-client
2) npm install @dydxprotocol/v3-client

Both install commands are temporarily creating a node_modules folder.
After ending the command the node_modules folder vanishes.
Command 1 has no CLI output.
Command 2 is showing a lot of ERR messenges.
What can I do please ?
Thx :-)

**Comment by sniper365** [comment]
Sorry for reopening this issue
But I also can't install dydxprotocol/v3-client.
Would you please help us?
