### ISSUE TITLE
Install not working and Can we see updated Readme.md

### ISSUE THREAD

**Issue by sniper365** [dydxprotocol/v3-client#216]
Hi 
Install not working for me. The issues are same with #157
Would you please help me?

**Comment by Ulawun** [comment]
Hello sniper365,
I'm very sorry to say,
that I didn't find a solution till now.
Because of this install issue
I cancelled the project.
If you find a solution,
please let me know.
Good luck :-)

**Comment by sniper365** [comment]
Sure

Dydx will help us for sure!!

**Comment by sniper365** [comment]
Installed successfully

one more thing..

Could you update readme.md for enough usage?

**Comment by Ulawun** [comment]
Hey great. Congrats.
Please tell me,
how can I "update readme.md for enough usage" ?

**Comment by sniper365** [comment]
I asked the team that could they update the ReadMe.md so that we can use this library

**Comment by sniper365** [comment]
No trick

**Comment by sniper365** [comment]
npm i -s @dydxprotocol/v3-client

**Comment by sniper365** [comment]
I said I hope they would update readme.md so that we can easily use this repo

**Comment by sniper365** [comment]
from ca?

**Comment by sniper365** [comment]
> Now npm i -s @dydxprotocol/v3-client works for me :-) Looks like the dydx team made some changes. Now I can think of continuing my projekt from ca. one year ago... Good luck with all your projects :-)

Plz ping me via pufstech@gmail.com

**Comment by sniper365** [comment]
Hi @Ulawun 

How is it going?

Ever met [this error](https://github.com/dydxprotocol/v3-client/issues/116#issuecomment-1426875359)?

**Comment by goodstemy** [comment]
@sniper365 after an hour of debugging i found a solution. Working on my macbook m1 with:
`-> node -v
v18.13.0`

Another version of node.js doesn't work for me.
My opinion is that at least the node.js version should be in the README. At the moment it looks like a mockery of users.
